#!/bin/bash

# this is a simple config for herbstluftwm

dir=~/.config/herbstluftwm/

~/.bin/wp change
source ~/.colors
source $dir/config

function hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# tags
TAG_NAMES=( z x c v b n m )
TAG_KEYS=( z x c v b n m )


hc set default_frame_layout $default_frame_layout

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use "${TAG_NAMES[$i]}"
        hc keybind "$Mod-Shift-$key" move "${TAG_NAMES[$i]}"
    fi
done

# Quit or Reload
hc keybind Control-Alt-Delete quit
hc keybind $Mod-Control-r reload

# Closing or opening programs
hc keybind $Mod-w close_or_remove
hc keybind $Mod-Return spawn $terminal
hc keybind $Mod-d spawn dmenu_run -fn $font -nb $COLOR0 -sb $COLOR2 -sf "#000000"

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-Right use_index +1 --skip-visible
hc keybind $Mod-Left  use_index -1 --skip-visible
hc keybind $Mod-a use_previous

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1

hc keybind $Mod-u       spawn $dir/split vertical   $vertical_split
hc keybind $Mod-o       spawn $dir/split horizontal $horizontal_split

hc keybind $Mod-Shift-u       spawn $dir/split vertical $vertical_split_i
hc keybind $Mod-Shift-o       spawn $dir/split horizontal $horizontal_split_i

hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-i spawn $dir/sidebar.sh
hc keybind $Mod-0 spawn $dir/padding

# resizing
RESIZESTEP=0.05
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-slash   cycle_monitor
hc keybind $Mod-Tab         cycle_all --skip-invisible +1
hc keybind $Mod-Shift-Tab   cycle_all --skip-invisible -1
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right
hc keybind $Mod-Shift-i rotate

hc keybind $Mod-Alt-h spawn $dir/swap left
hc keybind $Mod-Alt-j spawn $dir/swap down
hc keybind $Mod-Alt-k spawn $dir/swap up
hc keybind $Mod-Alt-l spawn $dir/swap right

hc keybind $Mod-equal spawn dm-tool lock


# colors
hc set window_border_active_color "$COLOR9"
hc set window_border_normal_color '#444444'

# settings
hc set default_frame_layout $default_frame_layout

hc set focus_follows_mouse $focus_follows_mouse 
hc set focus_stealing_prevention 0
hc set raise_on_click $raise_on_click 
hc set raise_on_focus $raise_on_focus 
hc set raise_on_focus_temporarily $raise_on_focus_temporarily 

hc set window_gap $window_gap
hc set frame_gap $frame_gap
hc set frame_padding $frame_padding

hc set frame_border_width $frame_border_width 
hc set window_border_width $window_border_width 
hc set window_border_inner_width $window_border_inner_width 
hc set frame_bg_transparent $frame_bg_transparent 
hc set frame_active_opacity $frame_active_opacity 
hc set frame_normal_opacity $frame_normal_opacity 

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # Focus new windows by default

# focus and psudotile dialogs
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' \
  pseudotile=on

hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

hc rule class=URxvt pseudotile=on

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

hc detect_monitors

$dir/panel/panel.sh &
