#!/bin/bash
# autostart

# starting to breakout the theme config vareables
font="iceland-11"
bg_dark="#2c2c2c"
green="#56e202"
terminal="gnome-terminal"

# this is a simple config for herbstluftwm
dir=~/.config/herbstluftwm/

function hc() {
    herbstclient "$@"
}

hc emit_hook reload


#monitors
sh $dir/xrandr_set_monitor.sh # if xrandr is set will make one screen for each monitor
awsetbg ~/backgrounds/ -r # pick a random background

# Bars
sh $dir/bar.sh # will add a clock and workspace bar to every screen
               # and a stalone tray for the main screen (the 0th screen)

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn $terminal
hc keybind $Mod-d spawn dmenu_run -fn $font -nb $bg_dark -sb $green -sf '#000000'
hc keybind $Mod-Control-r spawn $dir/rename_tag # spawns dmenu to change name of tag
hc keybind $Mod-0 spawn $dir/padding

# tags
TAG_NAMES=( {1..9} )
TAG_KEYS=( {1..9} 0 )

hc set default_frame_layout 1
hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use "${TAG_NAMES[$i]}"
        hc keybind "$Mod-Shift-$key" move "${TAG_NAMES[$i]}"
    fi
done

# it's quite possible i've misuderstood something fundamental about herb
# this script removes the extra tags added when you reload autostart
# and readds bindings to any tags you renamed
sh $dir/reset_bindings $Mod

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.05
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-slash   cycle_monitor
hc keybind $Mod-Tab         cycle +1
hc keybind $Mod-Shift-Tab   cycle -1
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# settings
hc set focus_follows_mouse 1

# colors
hc set frame_border_active_color '#2c2c2c'
hc set frame_border_normal_color '#121212'
hc set frame_bg_normal_color '#000000'
hc set frame_bg_active_color '#000000'
hc set frame_border_width 1
hc set window_border_width 2
hc set frame_bg_transparent 1
hc set window_border_active_color '#cf015e'
hc set window_border_normal_color '#444444'

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally do focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off



