#!/bin/bash

background=$(find $1 -type f \( -name '*.jpg' -o -name '*.png' \) -print0 | shuf -n1 -z | xargs -0)
filename=$(basename $background)
dirname=$(dirname $background)
echo $background
feh --bg-scale $background

ln -f $dirname/.$filename.colors ~/.colors
xrdb $dirname/.$filename.Xres
#xrdb ./solarized.Xres
