#!/bin/bash

export Mod=Mod4

export font="terminus-10"
export terminal="urxvt"
export browser="chromium"


export default_frame_layout=l

export focus_follows_mouse=1
export raise_on_click=1
export raise_on_focus=0
export raise_on_focus_temporarily=0

export frame_border_width=0
export window_border_width=2
export frame_gap=4

export frame_bg_transparent=1
export frame_active_opacity=1
export frame_normal_opacity=1

export vertical_split=0.82
export horizontal_split=0.62
