#!/bin/bash

source ~/.colors

dir=~/.config/herbstluftwm/
source ~/.colors

function hc() {
    herbstclient "$@"
}
font="terminus-9"

hc set window_gap `echo -e "0\n6\n10\n16\n" | dmenu -fn $font -nb "$COLOR0" -sb "$COLOR2" -sf '#000000'`
