#!/bin/bash

dir=~/.config/herbstluftwm/
source ~/.colors

function hc() {
    herbstclient "$@"
}

hc set frame_gap `echo -e "0\n6\n10\n16\n" | dmenu -fn iceland-11 -nb "$COLOR0" -sb "$COLOR2" -sf '#000000'`

