#!/bin/bash
# rename_tag

source ~/.colors

###                                                 ###
## Script to rename tag without breaking keybindings ##
##                                                   ##
## TODO add hooks to update status bar               ##
###                                                 ###

dir=/home/caleb/.config/herbstluftwm/

function hc() {
    herbstclient "$@"
}

# these should be simplified
# get current tag
tag=`hc list_monitors | grep [FOCUS] | egrep \".*\" -o | sed 's/.\(.*\)./\1/'`
#get current key bindings
use=`hc list_keybinds | egrep use[[:space:]]*$tag | egrep -o '^[^[:space:]]*'`
move=`hc list_keybinds | egrep move[[:space:]]*$tag | egrep -o '^[^[:space:]]*'`

# get the name of the new tag
new_tag=`dmenu -fn iceland-11 -nb "$COLOR0" -sb "$COLOR0" -sf '#000000' < $dir/cache/tags`

if [ "$new_tag" != "" ] ; then
  echo $new_tag > $dir/cache/tags.tmp

  if ! hc tag_status | grep $new_tag
  then
    hc rename $tag $new_tag
    hc keybind $use use $new_tag
    hc keybind $move move $new_tag
  fi


  # cacheing stuff
  for name in `cat $dir/cache/tags`
  do
    if [ "$new_tag" != "$name" ] ; then
      echo $name >> $dir/cache/tags.tmp
    fi
  done
  mv $dir/cache/tags.tmp $dir/cache/tags
fi
