#!/bin/bash

dir=/home/caleb/.config/herbstluftwm/

function hc() {
    herbstclient "$@"
}

Mod=$1
N=1
for i in `hc tag_status`
do
  tag=`echo $i | sed 's/.\(.*\)/\1/'`
  if [ "$N" -le "9" ] ; then
    echo $Mod-$N use $tat
    hc keybind "$Mod-$N" use "$tag"
    hc keybind "$Mod-Shift-$N" move "$tag"
  else
    hc merge_tag $tag
  fi
  let "N= $N + 1"
done

