#!/bin/bash
# Split Current window and shift the selected window into the new split

function hc() {
    herbstclient "$@"
}

if [[ "$1" -ne "horizontal" && "$1" -ne "vertical" ]]; then
  exit 1
fi

if [[ "$1" -eq "horizontal" ]]; then
  direction="right"
elif [[ "$1" -eq "vertical" ]]; then
  direction="down"
fi

hc lock

hc split $1 $2
hc shift -e $direction

hc unlock
