#!/bin/bash
# ws_bar

###                                                            ###
## This script populates the info for the workspace bar.        ##
## It updates whenever a hook with the word tag in it is emited ##
## currently supports clicking on tag names to switch tags      ##
###                                                            ###

bg_empty="#2c2c2c" # light grey
bg_focus="#cf015e" # pink
bg_occup="#1c1c1c" # dark grey

while [ ! -t 1 ] # close if not piped anywhere, or pipe is exited
do
  ws=""
  tags=`herbstclient tag_status $1`
  N=1
  for tag in $tags ; do
    char=${tag:0:1} # get tag type
    tag=${tag:1}    # get tag name
    
	# use this if you dont want numbered tags
	#tag=" $tag " # padding

	# use this if you do want numbered tags
	if [ "$N" == "$tag" ] ; then
		tag=" $tag " # padding
	else
		tag=" $N: $tag " # padding
	fi

    # Comment this out if your dzen doesnt support clickable areas
	# if your workspace bar is filled with junk comment this out
	# or download the newest version of dzen (dzen-svn in the AUR)
    tag="^ca(1, herbstclient use $tag)$tag^ca()" 

    # set tag colors
    if [ "$char" == ":" ] ; then # occupied unfocused tag
      tag="^bg($bg_occup)$tag"
    elif [ "$char" == "#" ] || [ "$char" == "+" ]; then # focused tags
      tag="^bg($bg_focus)$tag"
    elif [ "$char" == '.' ] ; then # empty tag
      tag="^bg($bg_empty)$tag"
    fi

    ws="$ws$tag"
	let "N= $N + 1"
  done
  echo "$ws^bg($bg_empty)"
  herbstclient -w tag > /dev/null # wait for a tag hook to update again
done

echo $1
exit
